### ISSUE TITLE
Mobile fixes

### ISSUE THREAD

**Issue by markotarnaj** [Jaspero/exo#121]

**Comment by markotarnaj** [comment]
<img width="928" alt="Screenshot 2020-04-23 at 10 14 23" src="https://user-images.githubusercontent.com/21045225/80076434-7d096d80-854c-11ea-98f5-ebd4eb08648f.png">

**Comment by markotarnaj** [comment]
This looks a bit strange. Try center alignment on all, and increase top and bottom padding.

<img width="376" alt="Screenshot 2020-04-23 at 10 24 30" src="https://user-images.githubusercontent.com/21045225/80076647-c954ad80-854c-11ea-82f5-6ed7812739a4.png">

**Comment by markotarnaj** [comment]
"Scroll down" and "Experience" - contrast too low.

<img width="378" alt="Screenshot 2020-04-23 at 10 27 30" src="https://user-images.githubusercontent.com/21045225/80076884-0f117600-854d-11ea-9c6c-f3ac2a53176d.png">

**Comment by markotarnaj** [comment]
This section looks strange. Image is possibly too large. Image should possibly go after the title. Space between text and button is too large. Left and right padding is too small. Title is too large.

<img width="456" alt="Screenshot 2020-04-23 at 10 37 30" src="https://user-images.githubusercontent.com/21045225/80077915-75e35f00-854e-11ea-85f5-66bedcda81b1.png">

**Comment by markotarnaj** [comment]
Order of things is off. Home should be first

<img width="414" alt="Screenshot 2020-04-23 at 10 40 47" src="https://user-images.githubusercontent.com/21045225/80078243-ea1e0280-854e-11ea-9c6c-7968a1a12a13.png">

**Comment by Siclol** [comment]
In general left and right padding is a bit too small across the whole website.

<img width="416" alt="Screenshot 2020-04-23 at 10 43 25" src="https://user-images.githubusercontent.com/21045225/80078532-5567d480-854f-11ea-976e-bf8b83bdd83b.png">

**Comment by markotarnaj** [comment]
The text on this segment looks way off from the others on mobile. Maybe make the text same as the rest of the stuff?

<img width="412" alt="Screenshot 2020-04-23 at 11 03 17" src="https://user-images.githubusercontent.com/21045225/80084338-07ef6580-8557-11ea-8e46-fca93fe2842f.png">

**Comment by markotarnaj** [comment]
The black box is full width and looks strange. Maybe reduce the height of the whole thing and add some horizontal paddings?

<img width="415" alt="Screenshot 2020-04-23 at 11 40 23" src="https://user-images.githubusercontent.com/21045225/80084500-3e2ce500-8557-11ea-965a-0c53d494e97c.png">

**Comment by markotarnaj** [comment]
Space between title and image is too small OR space between title and text is too large.

<img width="408" alt="Screenshot 2020-04-23 at 11 43 19" src="https://user-images.githubusercontent.com/21045225/80084804-a7145d00-8557-11ea-9992-2b0114c9ff25.png">

**Comment by markotarnaj** [comment]
Individual items aren't visually separated. There's no indication where one item starts and where it ends. This can be achieved with white space or some kinds of separator or both.

<img width="606" alt="Screenshot 2020-04-23 at 11 56 10" src="https://user-images.githubusercontent.com/21045225/80086050-72a1a080-8559-11ea-9898-9523c04149f6.png">

**Comment by markotarnaj** [comment]
Alignment

<img width="410" alt="Screenshot 2020-04-23 at 11 58 28" src="https://user-images.githubusercontent.com/21045225/80086276-c318fe00-8559-11ea-8026-bfdbdcc155de.png">

**Comment by markotarnaj** [comment]
It looks strangle that one segment is in a smaller container and the other one isn't (form is full width, but working hours aren't).

<img width="410" alt="Screenshot 2020-04-23 at 11 59 10" src="https://user-images.githubusercontent.com/21045225/80086360-df1c9f80-8559-11ea-96a7-16da55d581f5.png">

**Comment by markotarnaj** [comment]
Stuff in footer is causing overflow-x

<img width="413" alt="Screenshot 2020-04-23 at 12 03 13" src="https://user-images.githubusercontent.com/21045225/80086727-6c5ff400-855a-11ea-80d2-8108431c6dd2.png">

**Comment by markotarnaj** [comment]
This segment needs some love

<img width="407" alt="Screenshot 2020-04-23 at 12 05 18" src="https://user-images.githubusercontent.com/21045225/80086966-be087e80-855a-11ea-976c-e1a2d966925f.png">

**Comment by markotarnaj** [comment]
Adjust this everywhere.

<img width="611" alt="Screenshot 2020-04-23 at 12 10 11" src="https://user-images.githubusercontent.com/21045225/80087466-66b6de00-855b-11ea-82f6-d150c67c6798.png">
